apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-pv
spec:
  capacity:
    storage: {{ .Values.mariadb.persistence.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mariadb