name: 'Helm - Deployement'

env:
  HELM_MARIADB_CHART_PATH: "./mariadb"
  HELM_MARIADB_RELEASE: "mariadb-wp"
  HELM_WORDPRESS_CHART_PATH: "./wordpress"
  HELM_WORDPRESS_RELEASE: "wordpress"
  NAMESPACE: "wordpress-namespace"

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  lint-with-install:
    name: 'Helm: Lint with Run Installation (kind cluster)'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure K8S cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Get nodes K8S cluster
        uses: actions-hub/kubectl@master
        with:
          args: get nodes

      - name: Create namespace
        uses: actions-hub/kubectl@master
        with:
          args: create namespace ${{ env.NAMESPACE }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Run lint - MariaDB
        id: lint-mariadb
        run: helm lint ${{ env.HELM_MARIADB_CHART_PATH }}

      - name: Run Installation - MariaDB
        id: install-mariadb
        run: |
          helm install ${{ env.HELM_MARIADB_RELEASE }} -n ${{ env.NAMESPACE }} ${{ env.HELM_MARIADB_CHART_PATH }}

      - name: Run lint - WordPress
        id: lint-wordpress
        run: helm lint ${{ env.HELM_WORDPRESS_CHART_PATH }}


      - name: Run Installation - WordPress
        id: install-wordpress
        run: |
          helm install ${{ env.HELM_WORDPRESS_RELEASE }} -n ${{ env.NAMESPACE }} ${{ env.HELM_WORDPRESS_CHART_PATH }}
          echo "TEST"